experiment_name: "clipper_benchmark_test"
experiment_type: CLIPPER_BENCHMARK
ply_path: "data/bun10k.ply"
seed: 0
# Bounded normal noise parameters
noise_sigma: 0.01
noise_beta: 0.0554
# Sweep parameters
num_assocs: [200]
outlier_ratios: [0.2]
num_trials: 10
# turn off results storage
save_results: False
data_association_config:
  invariant_sigma: 0.015
  invariant_epsilon: 0.05
