verbose: True
debug: True
registration_config:
  certify: True
  verbose: True
  adjust_cost: True
  # Analytic centering parameters
  ac_params:
    verbose: True
    lin_solver: MFCG_LRP
    lin_solve_max_iter: 200
    lin_solve_tol: 1e-5
    delta: 1e-5
    rescale_lin_sys: False
    max_iter: 20
    # Early stopping local
    early_stop_angle: True
    max_angle: 1e-3
    # Perturbation parameters
    perturb_constraints: False
    perturb_cost: True
    eps_cost: 1e-5
    # Preconditioner parameters
    lrp_params:
      tau: 1e-4
      method: SparseLDLT
    # Adaptive perturbation
    adaptive_perturb: False
    eps_mult_min: 1e-3
feature_extractor_config:
  max_num_keypoints: 512
data_association_config:
  certify: True
  method: CLIPPER_SDP
  unweighted: False
  invariant_epsilon: 0.20
  invariant_sigma: 0.05
  ransac_inlier_threshold: 0.1
  # Analytic Centering parameters
  ac_params:
    verbose: True
    lin_solver: MFCG_LRP
    lin_solve_max_iter: 400
    lin_solve_tol: 1e-5
    delta: 1e-6
    rescale_lin_sys: False
    max_iter: 20
    # Early stopping local
    early_stop_angle: True
    max_angle: 5e-4
    # Perturbation parameters
    perturb_constraints: True
    perturb_cost: True
    eps_cost: 1e-6
    eps_constr: 1e-6
    # Preconditioner parameters
    lrp_params:
      tau: 1e-6
      method: SparseLDLT
    # Adaptive perturbation
    adaptive_perturb: True
    eps_mult_min: 1e-3